const db = require("../config/db");

// CREATE REPORT
const createReport = async (data) => {
  const {
    exhibition_id,
    generated_by,
    report_type,
    file_path,
  } = data;

  // 1. Validation
  if (!exhibition_id || !generated_by || !report_type) {
    return {
      success: false,
      statusCode: 400,
      message: "Exhibition ID, generated by and report type are required",
    };
  }

  // 2. Check Exhibition Exists
  const [exhibition] = await db.query(
    `SELECT exhibition_id
     FROM exhibitions
     WHERE exhibition_id = ?`,
    [exhibition_id]
  );

  if (exhibition.length === 0) {
    return {
      success: false,
      statusCode: 404,
      message: "Exhibition not found",
    };
  }

  // 3. Check User Exists
  const [user] = await db.query(
    `SELECT user_id
     FROM users
     WHERE user_id = ?`,
    [generated_by]
  );

  if (user.length === 0) {
    return {
      success: false,
      statusCode: 404,
      message: "User not found",
    };
  }

  // 4. Create Report
  const [result] = await db.query(
    `INSERT INTO reports
    (
      exhibition_id,
      generated_by,
      report_type,
      file_path
    )
    VALUES (?, ?, ?, ?)`,
    [
      exhibition_id,
      generated_by,
      report_type,
      file_path || null,
    ]
  );

  return {
    success: true,
    statusCode: 201,
    message: "Report created successfully",
    reportId: result.insertId,
  };
};


// GET ALL REPORTS
const getAllReports = async () => {
  const [rows] = await db.query(
    `SELECT
       r.*,
       e.title AS exhibition_name,
       u.name AS generated_by_name,
       u.email AS generated_by_email
     FROM reports r
     JOIN exhibitions e
       ON r.exhibition_id = e.exhibition_id
     JOIN users u
       ON r.generated_by = u.user_id
     ORDER BY r.generated_at DESC`
  );

  return {
    success: true,
    statusCode: 200,
    data: rows,
  };
};


// GET REPORT BY ID
const getReportById = async (id) => {
  const [rows] = await db.query(
    `SELECT
       r.*,
       e.title AS exhibition_name,
       u.name AS generated_by_name,
       u.email AS generated_by_email
     FROM reports r
     JOIN exhibitions e
       ON r.exhibition_id = e.exhibition_id
     JOIN users u
       ON r.generated_by = u.user_id
     WHERE r.report_id = ?`,
    [id]
  );

  if (rows.length === 0) {
    return {
      success: false,
      statusCode: 404,
      message: "Report not found",
    };
  }

  return {
    success: true,
    statusCode: 200,
    data: rows[0],
  };
};


// DELETE REPORT
const deleteReport = async (id) => {
  const [report] = await db.query(
    `SELECT report_id
     FROM reports
     WHERE report_id = ?`,
    [id]
  );

  if (report.length === 0) {
    return {
      success: false,
      statusCode: 404,
      message: "Report not found",
    };
  }

  await db.query(
    `DELETE FROM reports
     WHERE report_id = ?`,
    [id]
  );

  return {
    success: true,
    statusCode: 200,
    message: "Report deleted successfully",
  };
};


module.exports = {
  createReport,
  getAllReports,
  getReportById,
  deleteReport,
};